/* 엄청난 사냥꾼 되기 - all world actors are rendered procedurally on canvas. */
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),SAVE='greatHunterSurvivalV2';
const zones=[['오두막','cabin'],['자원 구간','resource'],['사슴 서식지','deer'],['늑대 서식지','wolf'],['곰 서식지','bear']];
const itemNames={wood:'목재',stone:'돌',iron:'철 광석',deerHide:'사슴 가죽',antler:'사슴 뿔',deerMeat:'사슴 고기',wolfHide:'늑대 가죽',tooth:'늑대 이빨',wolfMeat:'늑대 고기',bearHide:'곰 가죽',paw:'곰 발바닥',bearMeat:'곰 고기'};
const recipes=[{id:'spear',name:'철제 사냥창',text:'피해 +3, 사거리 +65',cost:{wood:5,stone:5,iron:3},damage:3,range:65},{id:'armor',name:'두꺼운 가죽 방어구',text:'곰의 치명상을 견딥니다',cost:{deerHide:4,wolfHide:3,antler:2},armor:true},{id:'fang',name:'늑대 이빨 창날',text:'피해 +2, 사거리 +45',cost:{tooth:5,iron:2},damage:2,range:45}];
const fresh=()=>({zone:0,hp:100,hunger:100,temp:100,clock:7,bag:Object.fromEntries(Object.keys(itemNames).map(k=>[k,0])),made:[]});
let state;try{let v=JSON.parse(localStorage.getItem(SAVE));state={...fresh(),...v,bag:{...fresh().bag,...v?.bag}}}catch{state=fresh()}const save=()=>localStorage.setItem(SAVE,JSON.stringify(state));
let W=0,H=0,last=0,clockTick=0,actors=[],drops=[],projectiles=[],keys={},stick={x:0,y:0},mouse={x:0,y:0},pending=false;
const player={x:0,y:0,r:16,angle:0,lastDash:-5000,dashEnd:0,invuln:0};
const $=s=>document.querySelector(s),bonus=()=>recipes.filter(r=>state.made.includes(r.id)).reduce((a,r)=>({damage:a.damage+(r.damage||0),range:a.range+(r.range||0),armor:a.armor||!!r.armor}),{damage:0,range:0,armor:false});
function resize(){canvas.width=W=innerWidth;canvas.height=H=innerHeight;if(!player.x){player.x=W*.5;player.y=H*.55}}addEventListener('resize',resize);resize();
function current(){return zones[state.zone]}function message(t){$('#message').textContent=t}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}

// Explicit physical resource-zone spawner: each node has a unique coordinate, type and durability.
function spawnResourceZone(){
  const layout=[
    ['tree',.17,.27,5],['tree',.43,.20,5],['tree',.73,.31,5],['tree',.30,.72,5],['tree',.79,.73,5],
    ['rock',.23,.48,4],['rock',.60,.61,4],['rock',.87,.52,4],['iron',.53,.36,6],['iron',.12,.78,6]
  ];
  actors=layout.map(([type,x,y,hp])=>({type,x:Math.round(x*W),y:Math.round(y*H),r:type==='tree'?30:25,hp,max:hp}));
}
function animal(type,x,y){let hp=type==='deer'?5:type==='wolf'?9:34;return{type,x:x??(100+Math.random()*(W-200)),y:y??(100+Math.random()*(H-190)),r:type==='bear'?38:type==='wolf'?23:19,hp,max:hp,dir:Math.random()*Math.PI*2,turn:0,angry:type==='bear',flee:false,attack:0}}
function spawnZone(){
  drops=[];projectiles=[];pending=false;let kind=current()[1];
  if(kind==='resource')return spawnResourceZone();
  if(kind==='deer')actors=Array.from({length:5},()=>animal('deer'));
  else if(kind==='wolf')actors=Array.from({length:4},()=>animal('wolf'));
  else if(kind==='bear')actors=[animal('bear',W*.70,H*.48)];
  else actors=[];
}
function addDrop(type,x,y,n=1){for(let i=0;i<n;i++)drops.push({type,x:x+(i-(n-1)/2)*14,y:y+10+(i%2)*9,life:0})}
function destroy(a){if(a.type==='tree')addDrop('wood',a.x,a.y,2);else if(a.type==='rock')addDrop('stone',a.x,a.y,2);else if(a.type==='iron')addDrop('iron',a.x,a.y,2);else{let loot=a.type==='deer'?['deerHide','antler','deerMeat']:a.type==='wolf'?['wolfHide','tooth','wolfMeat']:['bearHide','paw','bearMeat'];loot.forEach((v,i)=>addDrop(v,a.x+(i-1)*12,a.y))}message(a.type==='tree'||a.type==='rock'||a.type==='iron'?'자원이 바닥에 떨어졌습니다.':'사냥 성공! 전리품에 다가가세요.')}
function makeGrad(x,y,r,inner,outer){let q=ctx.createRadialGradient(x-r*.25,y-r*.3,r*.1,x,y,r);q.addColorStop(0,inner);q.addColorStop(.68,outer);q.addColorStop(1,'#10150f');return q}
function ellipse(x,y,rx,ry,fill,stroke='#1b160f'){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.stroke()}
function drawTree(a){ctx.save();ctx.shadowColor='#061006';ctx.shadowBlur=12;ctx.shadowOffsetY=8;let trunk=ctx.createLinearGradient(a.x-10,0,a.x+12,0);trunk.addColorStop(0,'#21150c');trunk.addColorStop(.42,'#8a5430');trunk.addColorStop(.7,'#3d2315');trunk.addColorStop(1,'#120c08');ctx.fillStyle=trunk;ctx.beginPath();ctx.moveTo(a.x-10,a.y+27);ctx.lineTo(a.x-7,a.y-20);ctx.lineTo(a.x+8,a.y-20);ctx.lineTo(a.x+13,a.y+27);ctx.closePath();ctx.fill();ctx.shadowBlur=0;for(let i=0;i<5;i++){ctx.strokeStyle=i%2?'#b9844e':'#2a160b';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(a.x-7+i*4,a.y+22);ctx.bezierCurveTo(a.x-10+i*3,a.y,a.x+7-i*2,a.y-8,a.x-4+i*3,a.y-19);ctx.stroke()}[[0,-40,29],[18,-18,25],[-20,-14,25],[1,-6,30]].forEach(([dx,dy,r])=>{ctx.fillStyle=makeGrad(a.x+dx,a.y+dy,r,'#839150','#273f22');ctx.beginPath();ctx.arc(a.x+dx,a.y+dy,r,0,7);ctx.fill();ctx.strokeStyle='#1c301b';ctx.stroke()});ctx.restore()}
function drawRock(a,iron=false){ctx.save();ctx.shadowColor='#080b08';ctx.shadowBlur=10;ctx.shadowOffsetY=6;ctx.beginPath();for(let i=0;i<7;i++){let ang=-Math.PI/2+i*Math.PI*2/7,rr=a.r*(.77+(i%3)*.12),x=a.x+Math.cos(ang)*rr,y=a.y+Math.sin(ang)*rr*.72;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fillStyle=makeGrad(a.x,a.y,a.r,iron?'#c98256':'#9c9b8e',iron?'#3b2927':'#363b38');ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=iron?'#ecaa6c':'#beb9a6';ctx.lineWidth=1.2;ctx.stroke();for(let i=0;i<6;i++){let px=a.x-13+(i*23)%28,py=a.y-11+(i*17)%23;ctx.strokeStyle=iron?'#5c241e':'#242a29';ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(px+7,py+4);ctx.stroke()}if(iron){ctx.shadowColor='#e26935';ctx.shadowBlur=8;ctx.fillStyle='#d46c3e';[[0,-5],[-9,7],[10,8]].forEach(([dx,dy])=>ellipse(a.x+dx,a.y+dy,4,3,'#e89654','#6f2f25'));ctx.shadowBlur=0}ctx.restore()}
function drawAnimal(a){ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.dir);ctx.shadowColor='#080805';ctx.shadowBlur=10;ctx.shadowOffsetY=6;let fur=a.type==='deer'?['#dca36b','#70472c']:a.type==='wolf'?['#a5a294','#41413a']:['#8c674b','#34261b'];ellipse(0,2,a.r,a.r*.62,makeGrad(0,0,a.r,fur[0],fur[1]));ctx.shadowBlur=0;ellipse(a.r*.68,-a.r*.25,a.r*.45,a.r*.37,makeGrad(a.r*.68,-a.r*.25,a.r*.45,fur[0],'#34271e'));ctx.fillStyle='#111';ctx.beginPath();ctx.arc(a.r*.92,-a.r*.31,2.2,0,7);ctx.fill();if(a.type==='deer'){ctx.strokeStyle='#e4d1a0';ctx.lineWidth=2;[-1,1].forEach(s=>{ctx.beginPath();ctx.moveTo(a.r*.76,-a.r*.53);ctx.lineTo(a.r*.62,-a.r*.95);ctx.lineTo(a.r*.47,-a.r*1.04);ctx.moveTo(a.r*.62,-a.r*.77);ctx.lineTo(a.r*.37,-a.r*.8);ctx.stroke()})}else{ctx.fillStyle=fur[1];ctx.beginPath();ctx.moveTo(a.r*.42,-a.r*.5);ctx.lineTo(a.r*.53,-a.r*.95);ctx.lineTo(a.r*.66,-a.r*.48);ctx.fill();ctx.beginPath();ctx.moveTo(a.r*.86,-a.r*.48);ctx.lineTo(a.r*.96,-a.r*.9);ctx.lineTo(a.r*1.05,-a.r*.35);ctx.fill()}for(let s of[-1,1]){ctx.strokeStyle=fur[1];ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-a.r*.35,s*a.r*.34);ctx.lineTo(-a.r*.5,s*a.r*.67);ctx.moveTo(a.r*.32,s*a.r*.34);ctx.lineTo(a.r*.18,s*a.r*.67);ctx.stroke()}ctx.restore();bar(a.x,a.y-a.r-15,38,a.hp/a.max,'#cf5548')}
function drawCabin(){let wall=ctx.createLinearGradient(0,0,0,H);wall.addColorStop(0,'#20150e');wall.addColorStop(.5,'#614027');wall.addColorStop(1,'#170f0a');ctx.fillStyle=wall;ctx.fillRect(0,0,W,H);for(let y=0;y<H;y+=28){ctx.fillStyle=y%56?'#59361f':'#3b2416';ctx.fillRect(0,y,W,23);ctx.strokeStyle='#1c1009';ctx.lineWidth=3;ctx.strokeRect(-8,y,W+16,23);for(let x=(y/28%2)*55;x<W;x+=110){ctx.strokeStyle='#8a5b32';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,y+8);ctx.bezierCurveTo(x+30,y+2,x+58,y+20,x+103,y+12);ctx.stroke()}}let fire={x:W*.5,y:H*.55};ctx.save();ctx.shadowColor='#ef8b31';ctx.shadowBlur=45;let glow=ctx.createRadialGradient(fire.x,fire.y,4,fire.x,fire.y,120);glow.addColorStop(0,'#ffdb7a99');glow.addColorStop(.32,'#e56b2c55');glow.addColorStop(1,'#e56b2c00');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(fire.x,fire.y,120,0,7);ctx.fill();ctx.shadowBlur=0;for(let r=0;r<5;r++){ctx.save();ctx.translate(fire.x,fire.y);ctx.rotate(r*.63);ctx.fillStyle=makeGrad(0,0,38,'#a96736','#251309');ctx.fillRect(-34,-5,68,10);ctx.restore()}ctx.fillStyle=makeGrad(fire.x,fire.y-10,30,'#fff0a1','#d13f1f');ctx.beginPath();ctx.moveTo(fire.x,fire.y+12);ctx.quadraticCurveTo(fire.x-28,fire.y-17,fire.x-7,fire.y-48);ctx.quadraticCurveTo(fire.x+5,fire.y-25,fire.x+9,fire.y-62);ctx.quadraticCurveTo(fire.x+31,fire.y-12,fire.x+12,fire.y+12);ctx.closePath();ctx.fill();ctx.restore();let bx=W*.5+96,by=H*.55-20;ctx.save();ctx.shadowColor='#050403';ctx.shadowBlur=12;ctx.fillStyle=makeGrad(bx,by,46,'#a36b3d','#241409');ctx.fillRect(bx-52,by-20,104,15);ctx.fillRect(bx-43,by-5,8,52);ctx.fillRect(bx+34,by-5,8,52);ctx.strokeStyle='#d3a269';ctx.strokeRect(bx-52,by-20,104,15);ctx.restore()}
function bar(x,y,w,v,color){ctx.fillStyle='#151713';ctx.fillRect(x-w/2,y,w,6);ctx.fillStyle=color;ctx.fillRect(x-w/2+1,y+1,(w-2)*clamp(v,0,1),4)}
function drawPlayer(){ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.angle);ctx.shadowColor='#050706';ctx.shadowBlur=9;ellipse(0,2,16,19,makeGrad(0,0,18,'#ddc598','#4d4635'));ctx.shadowBlur=0;ctx.fillStyle='#33483c';ctx.fillRect(-11,0,18,18);ctx.fillStyle='#c5a36d';ctx.fillRect(5,-15,19,4);ctx.restore();bar(player.x,player.y-31,42,state.hp/100,'#72b65b')}
function draw(now){let day=!(state.clock>=18||state.clock<6),bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,day?'#6e9b8b':'#101b2a');bg.addColorStop(1,day?'#273f2c':'#142016');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);if(current()[1]==='cabin')drawCabin();else{for(let i=0;i<60;i++){let x=(i*131)%W,y=(i*71)%H;ctx.fillStyle=i%3?'#39563a':'#5f7444';ctx.globalAlpha=.23;ctx.beginPath();ctx.arc(x,y,7+(i%4)*3,0,7);ctx.fill()}ctx.globalAlpha=1}actors.forEach(a=>a.type==='tree'?drawTree(a):a.type==='rock'?drawRock(a):a.type==='iron'?drawRock(a,true):drawAnimal(a));drops.forEach(d=>{ctx.save();ctx.shadowColor='#ffc957';ctx.shadowBlur=12;ellipse(d.x,d.y,8,6,makeGrad(d.x,d.y,9,'#fff0a0','#92542f'));ctx.restore()});projectiles.forEach(p=>{ctx.shadowColor='#ffe8a4';ctx.shadowBlur=8;ellipse(p.x,p.y,5,2,'#f8dd9a','#8b6334')});drawPlayer();if(!day){ctx.fillStyle='rgba(3,9,20,.48)';ctx.fillRect(0,0,W,H)}}
function updateUI(){['hp','hunger','temp'].forEach(k=>{$('#'+k+'Text').textContent=Math.ceil(state[k]);$('#'+k+'Bar').style.width=state[k]+'%'});$('#zoneName').textContent=current()[0];$('#packCount').textContent=Object.values(state.bag).reduce((a,b)=>a+b,0);$('#bag').innerHTML=Object.entries(itemNames).filter(([k])=>state.bag[k]).map(([k,n])=>'<div class="item"><span>'+n+'</span><b>× '+state.bag[k]+'</b></div>').join('')||'<div class="item">텅 빈 사냥 주머니</div>';$('#craft').innerHTML=recipes.map(r=>{let done=state.made.includes(r.id),ok=Object.entries(r.cost).every(([k,n])=>state.bag[k]>=n);return'<div class="recipe"><b>'+r.name+'</b><small>'+r.text+'<br>'+Object.entries(r.cost).map(([k,n])=>itemNames[k]+' '+state.bag[k]+'/'+n).join(' · ')+'</small><button class="craft" data-id="'+r.id+'" '+(done||!ok?'disabled':'')+'>'+ (done?'제작 완료':ok?'제작':'재료 부족')+'</button></div>'}).join('');document.querySelectorAll('.craft').forEach(e=>e.onclick=()=>{let r=recipes.find(v=>v.id===e.dataset.id);Object.entries(r.cost).forEach(([k,n])=>state.bag[k]-=n);state.made.push(r.id);save();updateUI();message(r.name+' 제작 완료!')});let h=Math.floor(state.clock),m=Math.floor((state.clock%1)*60).toString().padStart(2,'0');$('#timeLabel').textContent=(h>=18||h<6?'밤':'낮')+' · '+String(h).padStart(2,'0')+':'+m}
function interact(){if(current()[1]!=='cabin')return;let f=Math.hypot(player.x-W*.5,player.y-H*.55),b=Math.hypot(player.x-(W*.5+96),player.y-(H*.55-20));if(f<85){if(!state.bag.wood)return message('모닥불에 넣을 목재가 없습니다.');state.bag.wood--;state.temp=clamp(state.temp+48,0,100);save();message('장작을 넣어 불길이 되살아났습니다.');updateUI()}else if(b<80){$('#workbenchModal').hidden=false}else message('모닥불이나 제작대 가까이 다가가세요.')}
function attack(){state.hunger=clamp(state.hunger-.35,0,100);let b=bonus();projectiles.push({x:player.x+Math.cos(player.angle)*18,y:player.y+Math.sin(player.angle)*18,vx:Math.cos(player.angle)*510,vy:Math.sin(player.angle)*510,life:.42+b.range/310,damage:2+b.damage})}
function dash(now){if(now-player.lastDash<1300)return;player.lastDash=now;player.dashEnd=now+180;state.hunger=clamp(state.hunger-1,0,100)}
function hurt(amount,now){if(now<player.invuln)return;player.invuln=now+650;if(current()[1]==='bear'&&!bonus().armor)state.hp=0;else state.hp=clamp(state.hp-amount,0,100);if(!state.hp){state.hp=100;state.hunger=50;state.temp=70;state.zone=0;player.x=W*.5;player.y=H*.55;spawnZone();message('쓰러졌습니다. 오두막의 불빛이 당신을 깨웁니다.')}updateUI()}
function changeZone(d){let z=state.zone+d;if(z<0||z>=zones.length)return;state.zone=z;player.x=d>0?22:W-22;player.y=H*.55;spawnZone();save();updateUI();message(current()[0]+'에 진입했습니다.')}
function update(now,dt){state.clock=(state.clock+dt*.34)%24;let dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0)+stick.x,dy=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0)+stick.y,sp=now<player.dashEnd?490:165;if(dx||dy){let l=Math.hypot(dx,dy);player.x+=dx/l*sp*dt;player.y+=dy/l*sp*dt;state.hunger=clamp(state.hunger-dt*.42,0,100)}player.x=clamp(player.x,3,W-3);player.y=clamp(player.y,18,H-18);player.angle=Math.atan2(mouse.y-player.y,mouse.x-player.x);if(player.x<=4)changeZone(-1);if(player.x>=W-4)changeZone(1);let night=state.clock>=18||state.clock<6;if(night)state.temp=clamp(state.temp-dt*1.15,0,100);else state.temp=clamp(state.temp+dt*.17,0,100);if(current()[1]==='cabin'&&Math.hypot(player.x-W*.5,player.y-H*.55)<80)state.temp=clamp(state.temp+dt*5,0,100);if(!state.temp)state.hp=clamp(state.hp-dt*4,0,100);if(!state.hunger)state.hp=clamp(state.hp-dt*2,0,100);
 actors.forEach(a=>{if(!a.type.match(/deer|wolf|bear/))return;let d=dist(a,player),ang=Math.atan2(player.y-a.y,player.x-a.x);if(a.type==='deer'&&a.flee){a.x-=Math.cos(ang)*155*dt;a.y-=Math.sin(ang)*155*dt}else if((a.type==='bear'||a.angry)&&d<285){a.x+=Math.cos(ang)*(a.type==='bear'?70:88)*dt;a.y+=Math.sin(ang)*(a.type==='bear'?70:88)*dt;if(d<a.r+player.r+4)hurt(a.type==='bear'?999:12,now)}else{a.turn-=dt;if(a.turn<0){a.turn=.7+Math.random();a.dir=Math.random()*7}a.x+=Math.cos(a.dir)*28*dt;a.y+=Math.sin(a.dir)*28*dt}a.x=clamp(a.x,18,W-18);a.y=clamp(a.y,18,H-18)});
 projectiles.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;actors.forEach(a=>{if(q.hit||Math.hypot(q.x-a.x,q.y-a.y)>a.r+7)return;q.hit=true;a.hp-=q.damage;if(a.type==='deer')a.flee=true;if(a.type==='wolf'){actors.filter(v=>v.type==='wolf').forEach(v=>v.angry=true);message('늑대 무리가 울부짖으며 몰려듭니다!')}})});projectiles=projectiles.filter(q=>q.life>0&&!q.hit);actors.filter(a=>a.hp<=0).forEach(destroy);actors=actors.filter(a=>a.hp>0);drops=drops.filter(d=>{if(dist(d,player)<28){state.bag[d.type]++;save();updateUI();message(itemNames[d.type]+' 획득');return false}return true});if(!actors.length&&current()[1]!=='cabin'&&!pending){pending=true;setTimeout(()=>{if(!actors.length)spawnZone()},900)}clockTick+=dt;if(clockTick>.3){clockTick=0;updateUI()}draw(now)}
function loop(now){let dt=Math.min(.04,(now-last)/1000||0);last=now;update(now,dt);requestAnimationFrame(loop)}
addEventListener('keydown',e=>{keys[e.key]=true;if(e.code==='Space'||e.key==='Shift'){e.preventDefault();dash(performance.now())}if(e.key==='e'||e.key==='E')interact()});addEventListener('keyup',e=>keys[e.key]=false);canvas.addEventListener('mousemove',e=>{let r=canvas.getBoundingClientRect();mouse={x:e.clientX-r.left,y:e.clientY-r.top}});canvas.addEventListener('mousedown',e=>{if(e.button===0)attack()});
$('#packToggle').onclick=()=>$('#packPanel').hidden=!$('#packPanel').hidden;$('#closeBench').onclick=()=>$('#workbenchModal').hidden=true;$('#interact').onclick=interact;$('#cook').onclick=()=>{if(current()[1]!=='cabin'||Math.hypot(player.x-W*.5,player.y-H*.55)>85)return message('모닥불 가까이에서만 요리할 수 있습니다.');let meat=['bearMeat','wolfMeat','deerMeat'].find(k=>state.bag[k]);if(!meat)return message('구울 고기가 없습니다.');state.bag[meat]--;state.hunger=clamp(state.hunger+40,0,100);state.temp=clamp(state.temp+18,0,100);save();updateUI();message('고기를 구워 배고픔을 채웠습니다.')};$('#action').onclick=attack;$('#dash').onclick=()=>dash(performance.now());
let pad=$('#stick'),knob=pad.firstElementChild,id=null;function moveStick(e){let t=[...e.touches].find(v=>v.identifier===id),r=pad.getBoundingClientRect(),dx=t.clientX-r.left-r.width/2,dy=t.clientY-r.top-r.height/2,l=Math.min(42,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);stick={x:Math.cos(a)*l/42,y:Math.sin(a)*l/42};knob.style.transform='translate('+stick.x*30+'px,'+stick.y*30+'px)'}pad.addEventListener('touchstart',e=>{id=e.changedTouches[0].identifier;moveStick(e)},{passive:false});pad.addEventListener('touchmove',e=>{moveStick(e);e.preventDefault()},{passive:false});pad.addEventListener('touchend',()=>{id=null;stick={x:0,y:0};knob.style.transform=''});canvas.addEventListener('touchstart',e=>{let t=e.touches[0],r=canvas.getBoundingClientRect();mouse={x:t.clientX-r.left,y:t.clientY-r.top};attack()},{passive:true});
function updateCabinPrompt(){let active=false,label='상호작용';if(current()[1]==='cabin'){let fire=Math.hypot(player.x-W*.5,player.y-H*.55),bench=Math.hypot(player.x-(W*.5+96),player.y-(H*.55-20));if(fire<85){active=true;label='불 지피기 / 요리'}else if(bench<80){active=true;label='제작대 사용'}}$('#interact').hidden=!active;$('#interact').textContent=label}
setInterval(()=>{updateCabinPrompt();if(state.hp<=0)hurt(1,performance.now())},100);
setInterval(save,5000);spawnZone();updateUI();requestAnimationFrame(loop);
