// assets.png: 32px grid. Every canvas visual below is drawn only with this sprite sheet.
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),T=32,SAVE='greatHunterSpriteSurvivalV1';
const spriteImg=new Image();spriteImg.src='images/assets.png';
const cell=(col,row)=>[col*T,row*T,T,T];
const sprite={ground:cell(0,9),groundNight:cell(1,9),cabinFloor:cell(2,9),logWall:cell(3,9),player:cell(0,0),campfire:cell(1,0),workbench:cell(2,0),tree:cell(3,0),rock:cell(4,0),iron:cell(5,0),rabbit:cell(0,1),fox:cell(1,1),wolf:cell(2,1),bear:cell(3,1),boar:cell(4,1),deer:cell(5,1),lynx:cell(6,1),cougar:cell(7,1),dagger:cell(0,2),bow:cell(1,2),crossbow:cell(2,2),spear:cell(3,2),rifle:cell(4,2),axe:cell(5,2),meat:cell(0,3),hide:cell(1,3),tooth:cell(2,3),antler:cell(3,3),paw:cell(4,3),claw:cell(5,3),wood:cell(6,3),stone:cell(7,3),ironDrop:cell(0,4),projectile:cell(1,4)};
const zones=[['오두막','cabin'],['자원 구간','resource'],['일반 동물 서식지','plain'],['맹수 동물 서식지','predator'],['희귀 동물 서식지','rare']];
const names={wood:'나뭇가지/목재',stone:'돌',iron:'철광석',rabbitHide:'토끼 가죽',rabbitMeat:'토끼 고기',foxHide:'여우 가죽',foxMeat:'여우 고기',deerHide:'사슴 가죽',antler:'사슴 뿔',deerMeat:'사슴 고기',wolfHide:'늑대 가죽',tooth:'늑대 이빨',wolfMeat:'늑대 고기',bearHide:'곰 가죽',paw:'곰 발바닥',bearMeat:'곰 고기',boarHide:'멧돼지 가죽',tusk:'멧돼지 엄니',boarMeat:'멧돼지 고기',rareAntler:'희귀 사슴 뿔',claw:'시라소니 발톱',cougarHide:'쿠거 가죽',primeMeat:'최상급 고기'};
const recipes=[{id:'bow',name:'목재 활',txt:'피해 +1, 사거리 +35',cost:{wood:5,rabbitHide:2},dmg:1,range:35},{id:'spear',name:'철제 창',txt:'피해 +3, 사거리 +75',cost:{wood:5,stone:5,iron:3},dmg:3,range:75},{id:'crossbow',name:'대형 석궁',txt:'피해 +5, 사거리 +115',cost:{iron:6,tooth:5,wolfHide:3},dmg:5,range:115},{id:'rifle',name:'정밀 소총',txt:'피해 +8, 사거리 +175',cost:{iron:12,paw:2,claw:3},dmg:8,range:175},{id:'leather',name:'가죽 옷',txt:'맹수의 치명상 방어',cost:{deerHide:4,foxHide:3},armor:1},{id:'predator',name:'맹수 가죽 갑옷',txt:'피해 감소 +40%',cost:{wolfHide:4,bearHide:2,boarHide:3},armor:2},{id:'legend',name:'전설 사냥꾼 방어구',txt:'희귀 짐승의 치명상 방어',cost:{cougarHide:3,rareAntler:2,claw:4},armor:3}];
const blank=()=>({zone:0,hp:100,hunger:100,temp:100,time:7,bag:Object.fromEntries(Object.keys(names).map(k=>[k,0])),made:[]});
let state;try{let q=JSON.parse(localStorage.getItem(SAVE));state={...blank(),...q,bag:{...blank().bag,...q?.bag}}}catch{state=blank()}const save=()=>localStorage.setItem(SAVE,JSON.stringify(state));
let W=0,H=0,last=0,uiTimer=0,actors=[],drops=[],shots=[],keys={},touch={x:0,y:0},aim={x:0,y:0},waiting=false;
const player={x:0,y:0,r:17,angle:0,lastDash:-9000,dashUntil:0,hitUntil:0};const $=q=>document.querySelector(q),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),zone=()=>zones[state.zone],d=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function resize(){canvas.width=W=innerWidth;canvas.height=H=innerHeight;if(!player.x){player.x=W/2;player.y=H*.58}}addEventListener('resize',resize);resize();
function draw(s,x,y,w=T,h=T,flip=false,angle=0){if(!spriteImg.complete||!spriteImg.naturalWidth)return;ctx.save();ctx.translate(x+w/2,y+h/2);ctx.rotate(angle);ctx.scale(flip?-1:1,1);ctx.drawImage(spriteImg,s[0],s[1],s[2],s[3],-w/2,-h/2,w,h);ctx.restore()}
function mapSprite(type){return sprite[type==='iron'?'iron':type]||sprite.hide}function msg(t){$('#message').textContent=t}function stats(){return recipes.filter(r=>state.made.includes(r.id)).reduce((a,r)=>({dmg:a.dmg+(r.dmg||0),range:a.range+(r.range||0),armor:Math.max(a.armor,r.armor||0)}),{dmg:0,range:0,armor:0})}
// Resource objects are always explicitly placed in this function on resource-zone entry.
function spawnResourceZone(){const nodes=[['tree',.14,.25,5],['tree',.38,.19,5],['tree',.74,.28,5],['tree',.27,.74,5],['tree',.82,.70,5],['rock',.20,.50,4],['rock',.55,.63,4],['rock',.87,.48,4],['iron',.51,.34,6],['iron',.11,.76,6]];actors=nodes.map(([type,x,y,hp])=>({type,x:x*W,y:y*H,r:type==='tree'?31:25,hp,max:hp}))}
function animal(type){let hp={rabbit:3,fox:4,deer:6,wolf:10,bear:16,boar:11,lynx:13,cougar:16}[type];return{type,x:100+Math.random()*(W-200),y:110+Math.random()*(H-220),r:type==='bear'?36:type==='cougar'?27:22,hp,max:hp,dir:Math.random()*7,turn:0,angry:false,flee:false}}
function spawn(){drops=[];shots=[];waiting=false;let k=zone()[1];if(k==='resource')return spawnResourceZone();if(k==='plain')actors=['rabbit','fox','deer','deer','rabbit'].map(animal);else if(k==='predator')actors=['wolf','wolf','bear','boar'].map(animal);else if(k==='rare')actors=['deer','lynx','cougar'].map((t,i)=>animal(t));else actors=[]}
function itemSprite(item){if(item==='wood')return sprite.wood;if(item==='stone')return sprite.stone;if(item==='iron')return sprite.ironDrop;if(item.includes('Meat'))return sprite.meat;if(item.includes('Hide'))return sprite.hide;if(item==='tooth'||item==='tusk')return sprite.tooth;if(item.includes('antler'))return sprite.antler;if(item==='paw')return sprite.paw;if(item==='claw')return sprite.claw;return sprite.hide}
function die(a){let loot={tree:['wood','wood'],rock:['stone','stone'],iron:['iron','iron'],rabbit:['rabbitHide','rabbitMeat'],fox:['foxHide','foxMeat'],deer:['deerHide','antler','deerMeat'],wolf:['wolfHide','tooth','wolfMeat'],bear:['bearHide','paw','bearMeat'],boar:['boarHide','tusk','boarMeat'],lynx:['claw','primeMeat'],cougar:['cougarHide','primeMeat'],}[a.type]||[];loot.forEach((type,i)=>drops.push({type,x:a.x+(i-1)*14,y:a.y+10}));msg(a.type==='tree'||a.type==='rock'||a.type==='iron'?'채집 성공! 재료를 주우세요.':'사냥 성공! 전리품을 주우세요.')}
function render(){let night=state.time>=18||state.time<6,k=zone()[1],tile=k==='cabin'?sprite.cabinFloor:night?sprite.groundNight:sprite.ground;for(let y=0;y<H;y+=T)for(let x=0;x<W;x+=T)draw(tile,x,y,T,T);if(k==='cabin'){for(let x=0;x<W;x+=T)draw(sprite.logWall,x,0,T,T);draw(sprite.logWall,0,0,T,H);draw(sprite.logWall,W-T,0,T,H);draw(sprite.campfire,W/2-36,H*.55-36,72,72);draw(sprite.workbench,W/2+55,H*.55-43,86,86)}actors.forEach(a=>draw(mapSprite(a.type),a.x-a.r,a.y-a.r,a.r*2,a.r*2,a.dir>Math.PI/2&&a.dir<Math.PI*1.5,a.dir));drops.forEach(a=>draw(itemSprite(a.type),a.x-12,a.y-12,24,24));shots.forEach(a=>draw(sprite.projectile,a.x-7,a.y-7,14,14,false,a.angle));draw(sprite.player,player.x-22,player.y-22,44,44,false,player.angle);if(night)draw(sprite.groundNight,player.x-160,player.y-160,320,320)}
function updateUI(){['hp','hunger','temp'].forEach(k=>{$('#'+k+'Text').textContent=Math.ceil(state[k]);$('#'+k+'Bar').style.width=state[k]+'%'});$('#zoneName').textContent=zone()[0];$('#bagCount').textContent=Object.values(state.bag).reduce((a,b)=>a+b,0);$('#bag').innerHTML=Object.entries(names).filter(([k])=>state.bag[k]).map(([k,n])=>'<div class="item"><span>'+n+'</span><b>× '+state.bag[k]+'</b></div>').join('')||'<div class="item">비어 있습니다.</div>';$('#recipes').innerHTML=recipes.map(r=>{let made=state.made.includes(r.id),can=Object.entries(r.cost).every(([k,n])=>state.bag[k]>=n);return'<div class="recipe"><b>'+r.name+'</b><small>'+r.txt+'<br>'+Object.entries(r.cost).map(([k,n])=>names[k]+' '+state.bag[k]+'/'+n).join(' · ')+'</small><button class="craft" data-id="'+r.id+'" '+(made||!can?'disabled':'')+'>'+ (made?'완성':can?'제작':'재료 부족')+'</button></div>'}).join('');document.querySelectorAll('.craft').forEach(b=>b.onclick=()=>craft(b.dataset.id));let h=Math.floor(state.time),m=Math.floor(state.time%1*60).toString().padStart(2,'0');$('#clock').textContent=(h>=18||h<6?'밤':'낮')+' · '+String(h).padStart(2,'0')+':'+m}
function craft(id){let r=recipes.find(r=>r.id===id);Object.entries(r.cost).forEach(([k,n])=>state.bag[k]-=n);state.made.push(id);save();updateUI();msg(r.name+' 제작 완료!')}
function nearCabin(){if(zone()[1]!=='cabin')return null;if(Math.hypot(player.x-W/2,player.y-H*.55)<76)return'fire';if(Math.hypot(player.x-(W/2+98),player.y-(H*.55-2))<76)return'bench';return null}
function interact(){let n=nearCabin();if(n==='fire'){if(!state.bag.wood)return msg('모닥불에 넣을 목재가 없습니다.');state.bag.wood--;state.temp=clamp(state.temp+50,0,100);save();updateUI();msg('불씨가 살아나 체온이 급속히 회복됩니다.')}else if(n==='bench'){$('#workbench').hidden=false}else msg('상호작용할 오브젝트 가까이로 이동하세요.')}
function attack(){state.hunger=clamp(state.hunger-.35,0,100);let b=stats(),angle=player.angle;shots.push({x:player.x+Math.cos(angle)*24,y:player.y+Math.sin(angle)*24,vx:Math.cos(angle)*520,vy:Math.sin(angle)*520,angle,life:.42+b.range/300,damage:2+b.dmg})}
function dash(now){if(now-player.lastDash<1300)return;player.lastDash=now;player.dashUntil=now+180;state.hunger=clamp(state.hunger-1,0,100)}
function hurt(amount,now,rare=false){if(now<player.hitUntil)return;player.hitUntil=now+650;let armor=stats().armor;if((zone()[1]==='predator'&&!armor)||(rare&&armor<3))state.hp=0;else state.hp=clamp(state.hp-amount*(armor>1?.6:1),0,100);if(!state.hp){state.hp=100;state.hunger=45;state.temp=70;state.zone=0;player.x=W/2;player.y=H*.58;spawn();msg('쓰러졌습니다. 오두막의 화로에서 되살아났습니다.')}updateUI()}
function changeZone(dir){let next=state.zone+dir;if(next<0||next>=zones.length)return;state.zone=next;player.x=dir>0?22:W-22;player.y=H*.55;spawn();save();updateUI();msg(zone()[0]+'에 진입했습니다.')}
function update(now,dt){state.time=(state.time+dt*.32)%24;let dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0)+touch.x,dy=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0)+touch.y,speed=now<player.dashUntil?500:165;if(dx||dy){let l=Math.hypot(dx,dy);player.x+=dx/l*speed*dt;player.y+=dy/l*speed*dt;state.hunger=clamp(state.hunger-dt*.42,0,100)}player.x=clamp(player.x,2,W-2);player.y=clamp(player.y,18,H-18);player.angle=Math.atan2(aim.y-player.y,aim.x-player.x);if(player.x<=3)changeZone(-1);if(player.x>=W-3)changeZone(1);let night=state.time>=18||state.time<6;if(night)state.temp=clamp(state.temp-dt*1.2,0,100);if(nearCabin()==='fire')state.temp=clamp(state.temp+dt*5,0,100);if(!state.temp)state.hp=clamp(state.hp-dt*4,0,100);if(!state.hunger)state.hp=clamp(state.hp-dt*2,0,100);
 actors.forEach(a=>{if(['tree','rock','iron'].includes(a.type))return;let distance=d(a,player),ang=Math.atan2(player.y-a.y,player.x-a.x),pred=['wolf','bear','boar','lynx','cougar'].includes(a.type),rare=['lynx','cougar'].includes(a.type);if(a.flee){a.x-=Math.cos(ang)*(a.type==='deer'?180:145)*dt;a.y-=Math.sin(ang)*(a.type==='deer'?180:145)*dt}else if((pred&&(a.angry||distance<230))){a.angry=true;a.x+=Math.cos(ang)*(rare?130:80)*dt;a.y+=Math.sin(ang)*(rare?130:80)*dt;if(distance<a.r+player.r+3)hurt(rare?35:18,now,rare)}else{a.turn-=dt;if(a.turn<0){a.turn=.6+Math.random();a.dir=Math.random()*7}a.x+=Math.cos(a.dir)*30*dt;a.y+=Math.sin(a.dir)*30*dt}a.x=clamp(a.x,20,W-20);a.y=clamp(a.y,20,H-20)});
 shots.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;actors.forEach(a=>{if(q.hit||d(q,a)>a.r+8)return;q.hit=true;a.hp-=q.damage;if(['rabbit','fox','deer'].includes(a.type))a.flee=true;if(['wolf','bear','boar'].includes(a.type)){actors.filter(v=>['wolf','bear','boar'].includes(v.type)).forEach(v=>v.angry=true);msg('맹수들이 공격에 반응했습니다!')}})});shots=shots.filter(q=>q.life>0&&!q.hit);actors.filter(a=>a.hp<=0).forEach(die);actors=actors.filter(a=>a.hp>0);drops=drops.filter(a=>{if(d(a,player)<30){state.bag[a.type]++;save();updateUI();msg(names[a.type]+' 획득');return false}return true});if(!actors.length&&zone()[1]!=='cabin'&&!waiting){waiting=true;setTimeout(()=>{if(!actors.length)spawn()},1000)}uiTimer+=dt;if(uiTimer>.25){uiTimer=0;updateUI();let n=nearCabin();$('#interact').hidden=!n;$('#interact').textContent=n==='fire'?'불 지피기':'제작대 사용'}render()}
function loop(now){let dt=Math.min(.04,(now-last)/1000||0);last=now;update(now,dt);requestAnimationFrame(loop)}
addEventListener('keydown',e=>{keys[e.key]=true;if(e.code==='Space'||e.key==='Shift'){e.preventDefault();dash(performance.now())}if(e.key==='e'||e.key==='E')interact()});addEventListener('keyup',e=>keys[e.key]=false);canvas.addEventListener('mousemove',e=>{let r=canvas.getBoundingClientRect();aim={x:e.clientX-r.left,y:e.clientY-r.top}});canvas.addEventListener('mousedown',e=>{if(e.button===0)attack()});$('#bagToggle').onclick=()=>$('#bagPanel').hidden=!$('#bagPanel').hidden;$('#interact').onclick=interact;$('#closeWorkbench').onclick=()=>$('#workbench').hidden=true;$('#touchAction').onclick=attack;$('#touchDash').onclick=()=>dash(performance.now());$('#touchInteract').onclick=interact;
let joy=$('#joystick'),knob=joy.firstElementChild,touchId=null;function joyMove(e){let p=[...e.touches].find(v=>v.identifier===touchId),r=joy.getBoundingClientRect(),dx=p.clientX-r.left-r.width/2,dy=p.clientY-r.top-r.height/2,l=Math.min(42,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);touch={x:Math.cos(a)*l/42,y:Math.sin(a)*l/42};knob.style.transform='translate('+touch.x*30+'px,'+touch.y*30+'px)'}joy.addEventListener('touchstart',e=>{touchId=e.changedTouches[0].identifier;joyMove(e)},{passive:false});joy.addEventListener('touchmove',e=>{joyMove(e);e.preventDefault()},{passive:false});joy.addEventListener('touchend',()=>{touchId=null;touch={x:0,y:0};knob.style.transform=''});canvas.addEventListener('touchstart',e=>{let p=e.touches[0],r=canvas.getBoundingClientRect();aim={x:p.clientX-r.left,y:p.clientY-r.top};attack()},{passive:true});
function cook(){if(nearCabin()!=='fire')return msg('모닥불 가까이에서만 고기를 요리할 수 있습니다.');let meat=['primeMeat','bearMeat','boarMeat','wolfMeat','deerMeat','foxMeat','rabbitMeat'].find(k=>state.bag[k]);if(!meat)return msg('구울 고기가 없습니다.');state.bag[meat]--;state.hunger=clamp(state.hunger+42,0,100);state.temp=clamp(state.temp+18,0,100);save();updateUI();msg('고기를 구워 배고픔과 체온을 회복했습니다.')}
$('#cook').onclick=cook;setInterval(()=>{$('#cook').hidden=nearCabin()!=='fire'},120);
setInterval(save,5000);spawn();updateUI();requestAnimationFrame(loop);
