// assets.png uses 32x32 tiles: player(0,0), rabbit(32,0), wolf(64,0), drops y=32.
const c=document.querySelector('#game'),x=c.getContext('2d'),W=c.width,H=c.height,saveKey='topDownHunterV1';
const image=new Image();image.src='images/assets.png';
const tiles={player:[0,0],rabbit:[32,0],wolf:[64,0],meat:[0,32],leather:[32,32],fang:[64,32],iron:[96,32]};
const names={meat:'고기',leather:'가죽',fang:'송곳니',iron:'철광석'};
const grounds={1:{name:'숲 가장자리',color:'#315c39',types:['rabbit','rabbit','rabbit']},2:{name:'안개 낀 침엽수림',color:'#294838',types:['wolf','wolf','wolf','wolf']}};
const recipes=[{id:'bow',name:'사냥꾼의 활',text:'피해 +1 · 투사체 속도 +30%',cost:{leather:5,meat:3},dmg:1,spd:1.3},{id:'spear',name:'철제 창',text:'피해 +3 · 사거리 +90 · 2단계 해금',cost:{leather:5,fang:3,iron:3},dmg:3,range:90,unlock:2},{id:'strap',name:'늑대가죽 손목끈',text:'대시 재사용 시간 30% 감소',cost:{leather:7,fang:5},dash:.3}];
const fresh=()=>({bag:{meat:0,leather:0,fang:0,iron:0},made:[],weapon:'견습 활',ground:1});let state;try{let s=JSON.parse(localStorage.getItem(saveKey));state={...fresh(),...s,bag:{...fresh().bag,...s?.bag}}}catch{state=fresh()}const save=()=>localStorage.setItem(saveKey,JSON.stringify(state));
const B=()=>recipes.filter(r=>state.made.includes(r.id)).reduce((a,r)=>({dmg:a.dmg+(r.dmg||0),spd:a.spd*(r.spd||1),range:a.range+(r.range||0),dash:a.dash+(r.dash||0)}),{dmg:0,spd:1,range:0,dash:0});
let keys={},mouse={x:W/2,y:H/2},shots=[],animals=[],drops=[],last=performance.now(),respawnPending=false;const p={x:W/2,y:H/2,r:15,hp:100,max:100,angle:0,lastDash:-9999,dashEnd:0,invuln:0};
function note(t){document.querySelector('#notice').textContent=t}function spawn(){animals=grounds[state.ground].types.map((type,i)=>({type,x:80+Math.random()*(W-160),y:70+Math.random()*(H-140),r:type==='wolf'?18:14,hp:type==='wolf'?7:3,max:type==='wolf'?7:3,dir:Math.random()*6.28,turn:0}))}
function sprite(t,px,py,size,a=0){x.save();x.translate(px,py);x.rotate(a);let q=tiles[t];if(image.complete&&image.naturalWidth)x.drawImage(image,q[0],q[1],32,32,-size/2,-size/2,size,size);else{x.fillStyle=t==='player'?'#e0bb6f':t==='wolf'?'#777166':t==='rabbit'?'#d7a976':'#f0c865';x.fillRect(-size/2,-size/2,size,size)}x.restore()}function hp(px,py,w,r,col){x.fillStyle='#111b13';x.fillRect(px-w/2,py,w,5);x.fillStyle=col;x.fillRect(px-w/2,py,w*r,5)}
function draw(){x.fillStyle=grounds[state.ground].color;x.fillRect(0,0,W,H);x.globalAlpha=.15;x.strokeStyle='#d5bb72';for(let i=25;i<W;i+=75){x.beginPath();x.arc(i,(i*5)%H,20,0,7);x.stroke()}x.globalAlpha=1;drops.forEach(d=>{sprite(d.type,d.x,d.y,20);x.strokeStyle='#ffe18f';x.strokeRect(d.x-12,d.y-12,24,24)});animals.forEach(a=>{sprite(a.type,a.x,a.y,a.r*2,a.dir);hp(a.x,a.y-a.r-12,30,a.hp/a.max,'#d25548')});shots.forEach(s=>{x.fillStyle='#ffe18d';x.beginPath();x.arc(s.x,s.y,4,0,7);x.fill()});sprite('player',p.x,p.y,32,p.angle);hp(p.x,p.y-31,40,p.hp/p.max,'#76b757');x.strokeStyle='#f5d87d';x.beginPath();x.moveTo(p.x,p.y);x.lineTo(p.x+Math.cos(p.angle)*24,p.y+Math.sin(p.angle)*24);x.stroke()}
function update(dt){let n=Date.now(),b=B(),dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dy=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0),speed=n<p.dashEnd?500:150;if(dx||dy){let l=Math.hypot(dx,dy);p.x+=dx/l*speed*dt;p.y+=dy/l*speed*dt}p.x=Math.max(17,Math.min(W-17,p.x));p.y=Math.max(17,Math.min(H-17,p.y));p.angle=Math.atan2(mouse.y-p.y,mouse.x-p.x);animals.forEach(a=>{if((a.turn-=dt)<0){a.dir+=(Math.random()-.5)*1.8;a.turn=.5+Math.random()*1.5}a.x=Math.max(17,Math.min(W-17,a.x+Math.cos(a.dir)*35*dt));a.y=Math.max(17,Math.min(H-17,a.y+Math.sin(a.dir)*35*dt));if(Math.hypot(a.x-p.x,a.y-p.y)<a.r+p.r&&n>p.invuln){p.hp-=a.type==='wolf'?12:6;p.invuln=n+600;if(p.hp<=0){p.hp=100;p.x=W/2;p.y=H/2;note('쓰러졌지만 모닥불에서 회복했습니다.')}}});shots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;animals.forEach(a=>{if(!s.hit&&Math.hypot(s.x-a.x,s.y-a.y)<a.r+5){a.hp-=s.dmg;s.hit=true}})});shots=shots.filter(s=>s.life>0&&!s.hit);animals.filter(a=>a.hp<=0).forEach(a=>{let pool=a.type==='wolf'?['meat','leather','fang','iron']:['meat','leather'];drops.push({x:a.x,y:a.y,type:pool[Math.random()*pool.length|0]});note('사냥 성공! 빛나는 전리품에 다가가세요.')});animals=animals.filter(a=>a.hp>0);if(!animals.length&&!respawnPending){respawnPending=true;setTimeout(()=>{spawn();respawnPending=false},1000)}drops=drops.filter(d=>{if(Math.hypot(d.x-p.x,d.y-p.y)<30){state.bag[d.type]++;save();ui();note(names[d.type]+' 획득!');return false}return true});draw();requestAnimationFrame(t=>{let d=Math.min(.04,(t-last)/1000);last=t;update(d)})}
function attack(){let b=B(),a=p.angle;shots.push({x:p.x+Math.cos(a)*20,y:p.y+Math.sin(a)*20,vx:Math.cos(a)*360*b.spd,vy:Math.sin(a)*360*b.spd,dmg:2+b.dmg,life:.8+b.range/300})}function dash(){let now=Date.now(),cool=1500*(1-B().dash);if(now-p.lastDash>cool){p.lastDash=now;p.dashEnd=now+170;note('대시!')}}
function ui(){let b=B();document.querySelector('#ground').textContent=grounds[state.ground].name;document.querySelector('#weapon').textContent=state.weapon+' (피해 '+(2+b.dmg)+')';document.querySelector('#travel').textContent=state.ground===1?'안개 숲으로 이동':'숲 가장자리로 이동';document.querySelector('#travel').disabled=state.ground===1&&!state.made.includes('spear');document.querySelector('#bag').innerHTML=Object.entries(names).map(([k,v])=>'<div class="item"><span>'+v+'</span><b>× '+state.bag[k]+'</b></div>').join('');document.querySelector('#recipes').innerHTML=recipes.map(r=>{let made=state.made.includes(r.id),ok=Object.entries(r.cost).every(([k,v])=>state.bag[k]>=v);return '<article class="recipe"><h3>'+r.name+'</h3><p>'+r.text+'</p><div class="cost">'+Object.entries(r.cost).map(([k,v])=>names[k]+' '+state.bag[k]+'/'+v).join('<br>')+'</div><button class="craft" data-id="'+r.id+'" '+(made||!ok?'disabled':'')+'>'+ (made?'제작 완료':ok?'제작·장착':'재료 부족')+'</button></article>'}).join('');document.querySelectorAll('.craft').forEach(e=>e.onclick=()=>{let r=recipes.find(z=>z.id===e.dataset.id);Object.entries(r.cost).forEach(([k,v])=>state.bag[k]-=v);state.made.push(r.id);if(r.id==='bow')state.weapon='사냥꾼의 활';if(r.id==='spear')state.weapon='철제 창';save();ui();note(r.name+' 제작 완료!')})}
addEventListener('keydown',e=>{keys[e.key]=true;if(e.code==='Space'||e.key==='Shift'){e.preventDefault();dash()}});addEventListener('keyup',e=>keys[e.key]=false);c.onmousemove=e=>{let r=c.getBoundingClientRect();mouse={x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}};c.onmousedown=e=>{if(e.button===0)attack()};document.querySelector('#travel').onclick=()=>{state.ground=state.ground===1?2:1;save();spawn();ui();note(grounds[state.ground].name+'에 진입했습니다.')};document.querySelector('#reset').onclick=()=>{if(confirm('진행을 초기화할까요?')){state=fresh();save();spawn();ui()}};setInterval(()=>{let r=Math.max(0,1500*(1-B().dash)-(Date.now()-p.lastDash));document.querySelector('#dash').textContent=r?(r/1000).toFixed(1)+'초':'준비'},100);spawn();ui();requestAnimationFrame(t=>{last=t;update(0)});
